selenium:
  showLog: false
  # passthrough as selenium call arguments
  arguments: []

# passthrough for the wd.promiseChainRemote
wdRemote: ~

# passthrough for the wd.browser.init
browser:
  browserName: 'firefox'

onError:
  startNewBrowser: false
  takeScreenShot: false
  pause: false
  sleep: 0

runner:
  grep: ''
  exclude: manually
  startTestsWithNewBrowser: false
