selenium:
  showLog: false
  # passthrough as selenium call arguments
  arguments: []

# passthrough for the wd.promiseChainRemote
wdRemote: ~

# passthrough for the wd.browser.init
browser:
  browserName: 'firefox'

logger:
  # absolute path, relative from the root or relative from the module
  class: 'lib/logger.js'
  # passthrough to the logger constructor
  config:
    level: 'info'

onError:
  startNewBrowser: false
  takeScreenShot: false
  pause: false
  sleep: 0

runner:
  grep: ''
  exclude: manually
  startTestsWithNewBrowser: false
