include:
  - config.yml

onError:
  pause: false

testSuites:
  # this one run with the config from the main include
  AdaLovelace:

  CharlesBabbage:
    include:
      - config_charlesBabbage.yml

  DennisMRitchie:
    # everything is overrideable except the selenium and the testSuites configurations
    override:
      search:
        forWhat: 'Dennis M. Ritchie'
      logger:
        config:
          level: 'debug'

  onlyJavascript:
    override:
      # root also changeable with relative from the current root or absolute path
      root: ../end2endTests
      runner:
        grep: javascript/.+
